### ISSUE TITLE
Hub deployment fails with output issues when not using AD authentication

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/HubAndSpokeResearchEnclave#130]

**Comment by ludoll-uwm** [comment]
Possibly related, we are seeing this error string when attempting a deployment (looking to use Entra AD only, no on-premises AD ties):

Line |
81 |  $DeploymentResults = New-AzDeployment @CmdLetParameters
     |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 9:32:07 AM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The template output
     | reference to 'Microsoft.Resources/deployments/Hub-11-vm-mgmt-20241028T143207Z' requires an API version. Please
     | see https://aka.ms/arm-syntax for usage details.'.
